### ISSUE TITLE
Cold start times 

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/dps-website#119]
When a candidate is applying, most certainly they'll have to wait around 2-5seconds until the cloud functions start & process the application and this is annoying.

I wonder if we could have a cronjob firing at even intervals at the cloud function so it stays up? Or some other alternative to forbid cold starts?

**Comment by mstockerl** [comment]
I also only see the cronjob with an even interval as the option. As we do not have a constant traffic we need to keep it hot. 

This is also what [this article](https://medium.com/@siriwatknp/cold-start-workaround-in-firebase-cloud-functions-8e9db1426bd3) suggests. 
If this change is not enough, we can also try out to play with the imports as suggested in [this video](https://www.youtube.com/watch?v=v3eG9xpzNXM).

**Comment by lustoykov** [comment]
Here is a template for a cronjob on staging, it runs every minute. I'm not sure it's frequent enough - will see over time. Once we merge the new application flow, we should create one in production too.

https://console.cloud.google.com/cloudscheduler?project=dps-website-staging-0&authuser=1&organizationId=903600181628&jobs-tablesize=50
